### ISSUE TITLE
Addon request - ktuvit-stremio

### ISSUE THREAD

**Issue by TwilightMercy** [maormagori/wizdom-stremio-v2#16]
Hi,

your wizdom addon for Stremio is great!
Is there any chance of you developing addon for Ktuvit site?

Thanks

**Comment by maormagori** [comment]
Since this is a repeated request I'll answer here to leave no doubts.

A ktuvit add-on was in the making while I was working on this add-on three years ago. The difference between the two was that Ktuvit didn't make its API public (even though the content on the site is user generated).

To combat this I made the [ktuvit-api](https://github.com/maormagori/Ktuvit-api) repo which although being helpful wasn't working perfectly because Ktuvit limits the user to text search and not ID search.
I've contacted Ktuvit in past, trying to get access to their API but I didn't get any answers from them so I decided to abandon the Ktuvit add-on. 

Feel free to use any of my repos to create a ktuvit add-on, I'll might even join to help. But do think about the fact that Ktuvits only source of content (subtitles) is created and inputted by the community. For them to keep it unreachable is showing how they feel about their users and content creators.

Below is their response to my API request:
![Screenshot_20230227-134637_Chrome.jpg](https://user-images.githubusercontent.com/24867863/221626731-8b13deea-c2ba-4274-ae14-0260a9cfe3a8.jpg)

Still waiting for the relevent person...
